### ISSUE TITLE
Brightness doesn't increase when module is active 

### ISSUE THREAD

**Issue by idkman213** [reiryuki/DTSX-Ultra-ZTE-A2020G-Pro-Magisk-Module#1]
Running the zte module on the Nothing Phone (1) running nothingOS 1.1.2
i noticed a strange bug which made my phone not increase its brightness. The moment i slide the brightness slider, the screen flickers for some weird reason. I can provide logs if you need it in the replies

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module X
3) Full logcat X
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.

**Comment by idkman213** [comment]
Alright, sent a message on telegram with the required files.
