### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by babyharpsea** [reiryuki/DTSX-Ultra-ZTE-A2020G-Pro-Magisk-Module#2]
![Screenshot_20230616_161522_DTSX Ultra](https://github.com/reiryuki/DTSX-Ultra-ZTE-A2020G-Pro-Magisk-Module/assets/73757237/9224100c-0d2b-46c4-a366-0aa64357c513)

**Comment by babyharpsea** [comment]
![Screenshot_20230616_161551_DTSX Ultra](https://github.com/reiryuki/DTSX-Ultra-ZTE-A2020G-Pro-Magisk-Module/assets/73757237/1ffe27ce-d265-4795-99a1-227c5f0043b1)

**Comment by reiryuki** [comment]
Support & Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, issues will be ignored and closed immediately
